language: node_js
node_js:
  - "10"

before_install:
  - export TZ='Asia/Shanghai'

install:
  - npm install gitbook-cli -g
  - npm install -g gulp
  - npm link gulp
  - gitbook install

script:
  - gulp prebuild
  - gitbook build
  - gulp postbuild

deploy:
  provider: script
  skip_cleanup: true
  script: echo "hello"
  on:
    branch: master
