language: node_js
node_js:
- stable
before_install:
- export TZ='Asia/Shanghai'
install:
- yarn global add gitbook-cli
- yarn global add gulp-cli
- gitbook install
before_script:
- yarn
script:
- gulp prebuild
- gitbook build
- gulp postbuild
before_deploy:
- openssl aes-256-cbc -K $encrypted_ac1ee89ed3c7_key -iv $encrypted_ac1ee89ed3c7_iv
  -in .travis/ssh_config.enc -out /tmp/ssh_config -d
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
- cp /tmp/ssh_config ~/.ssh/
- cp .travis/known_hosts ~/.ssh/
deploy:
  provider: script
  skip_cleanup: true
  script: ".travis/deploy.sh"
  on:
    branch: master
