language: node_js
node_js:
  - "stable"

before_install:
  - export TZ='Asia/Shanghai'

install:
  - yarn global add gitbook-cli
  - yarn global add gulp-cli
  - gitbook install

before_script:
  - yarn

script:
  - gulp prebuild
  - gitbook build
  - gulp postbuild

deploy:
  provider: script
  skip_cleanup: true
  script: yarn sync
  on:
    branch: master
